version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      docker: 18
  pre_build:
    commands:
      - echo "Pre_build"
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login  --no-include-email --region us-east-1)
  build:
    commands:
      - echo "Build"
      - echo "Entered build phase"
      - echo "Building Java application"
      - cd  Medicine-Stock-MicroService
      - mvn -DskipTests clean package
      - docker build -t p3-Medicine-Stock-MicroService:latest .
      - docker tag p3-Medicine-Stock-MicroService:latest 234825976347.dkr.ecr.us-east-1.amazonaws.com/p3-Medicine-Stock-MicroService:latest

  post_build:
    commands:
      - echo "Post_build"
      - docker push 234825976347.dkr.ecr.us-east-1.amazonaws.com/p3-Authentication-service:latest
      - printf '[{"name":"p3-Medicine-Stock-MicroService-container","imageUri":"%s"}]' 234825976347.dkr.ecr.us-east-1.amazonaws.com/p3-Medicine-Stock-MicroService:latest > taskdefinition.json
      - cat taskdefinition.json

artifacts:
  files:
      - Medicine-Stock-MicroService/taskdefinition.json